-- local t = require(script.Parent.t)

return {

    Jail = "E"
    -- TweenInfo = t.strictInterface ({
    --     Time = t.numberMin(0.001),
    --     EasingStyle = t.callback,
    --     repeatCount = t.numberMin(-1),
    --     reverses = t.boolean,
    --     delayTime = t.number
    -- }),
    --                     -- Time         EasingStyle                 repeatcount         reverses                delaytime
    -- TweenInfoAgs = t.tuple(t.number, t.union(t.callback, t.table), t.optional(t.number), t.optional(t.boolean), t.optional(t.number))
}